### ISSUE TITLE
will it work with Magento message queue based on MySQL ?

### ISSUE THREAD

**Issue by onlinebizsoft** [run-as-root/magento2-message-queue-retry#16]
Magento officially support message queue using MySQL and RabbitMQ. Will this module work with Mysql-based queue? Thanks for this idea.

**Comment by cristiano-pacheco** [comment]
Hi @onlinebizsoft thank you for your question.

It supports only RabbitMQ queues, OK?

**Comment by onlinebizsoft** [comment]
@cristiano-pacheco do you have any idea how to get it working with MySQL adapter? Is it possible? I believe most of websites use Magento message queue based on MySQL instead of RabbitMQ.

**Comment by cristiano-pacheco** [comment]
Hi @onlinebizsoft it will not work with Mysql queues. This module works on top of the RabbitMQ dead letter exchange feature, Basically, the heavy lifting is done by RabbitMQ.

**Comment by onlinebizsoft** [comment]
@wilfriedwolf so your idea was catching exceptions and re-queue the job itself?

**Comment by wilfriedwolf** [comment]
Well basically in `\Magento\Framework\MessageQueue\Consumer::getTransactionCallback`  when the handler throws an error, the message ist rejected without requeueing:

```
           } catch (Exception $exception) {
                $queue->reject($message, false, $exception->getMessage());
                if ($lock) {
                    $this->resource->getConnection()->delete(
                        $this->resource->getTableName('queue_lock'),
                        ['id = ?' => $lock->getId()]
                    );
                }
            }
```

so I copied this Consumer and added another catch block just before

```
            } catch (DelayedException $exception) {
                $this->logger->warning($exception);
                $queue->reject($message);
                if ($lock) {
                    $this->resource->getConnection()
                        ->delete(
                            $this->resource->getTableName('queue_lock'),
                            ['message_code = ?' => $lock->getMessageCode()]
                        );
                }
            }
```
catching specially prepared exception for non permanent errors.

This approach is quite limited, since messages are basically requeued forever, so you better chose carefully to throw the `DelayedException`.
